apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: docker.io/yousufnizam/order:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30009