apiVersion: apps/v1
kind: Deployment
metadata:
  name: all
  labels:
    app: all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all
  template:
    metadata:
      labels:
        app: all
    spec:
      containers:
      - name: all
        image: docker.io/yousufnizam/all:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: NodePort
  selector:
    app: all
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  selector:
    app: all
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30011
---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  type: NodePort
  selector:
    app: all
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30012